!include ../shared_config.yaml

apps:
  - name: web-gateway
    app_module: solace_agent_mesh.gateway.http_sse.app
    broker:
      <<: *broker_connection
    app_config:
      namespace: ${NAMESPACE}
      session_secret_key: ${SESSION_SECRET_KEY}
      artifact_service: *default_artifact_service
      fastapi_host: ${FASTAPI_HOST}
      fastapi_port: ${WEB_GATEWAY_PORT}
      cors_allowed_origins: ["*"]
