"""Translate SAM `TaskStatusUpdateEvent` JSON into frontend-friendly event dicts.

Each SAM agent, when given an `a2aStatusTopic` user property on the
inbound A2A request, publishes JSON-RPC responses whose `result` is a
`TaskStatusUpdateEvent`. The inner `status.message.metadata.type`
discriminator tells us whether the update is an LLM invocation, an LLM
response, or a tool invocation start.

The frontend at `/case/<id>/building` expects a flatter shape keyed by
a short `event` string plus a few render fields (`content`, `tool_name`,
`args`, `result`). This module does the narrowing — anything we don't
recognise falls through as an `event: "unknown"` envelope carrying the
original SAM payload (clipped) so the UI's default `EventLine` branch
still renders something useful rather than dropping the message.
"""

from __future__ import annotations

import json
import re
from typing import Any

# Keep event payloads bounded so a chatty agent can't blow up the SSE
# queue or the browser. These caps line up with the frontend's own
# `.slice(0, N)` calls in BuildingSimulation.jsx.
_THINKING_CHAR_CAP = 600
_TOOL_ARGS_CHAR_CAP = 400
_RESULT_CHAR_CAP = 400

# logical_task_id is generated by mesh_runner as `<agent-name>-<run8>-<uuidhex>`.
# The first N dash-separated tokens before the 8-char run prefix give us the
# agent name. This keeps us independent of SAM's metadata.agent_name, which
# may be empty on some status updates.
_TASK_ID_AGENT_RE = re.compile(r"^(?P<agent>[a-z][a-z\-]*?)-(?P<run>[0-9a-f]{8})-")


def translate_sam_status(envelope: dict, *, case_id: str) -> dict | None:
    """Translate one SAM status JSON envelope into a frontend event dict.

    Returns None when the envelope is not a TaskStatusUpdateEvent wrapper
    (e.g. a peer artifact signal with no interesting content). Raises no
    exceptions on shape drift — callers are SSE stream producers and
    must not die on a single bad message.
    """
    result = envelope.get("result") if isinstance(envelope, dict) else None
    if not isinstance(result, dict):
        return None

    status = result.get("status") or {}
    message = status.get("message") or {}
    inner_metadata = message.get("metadata") or {}
    outer_metadata = result.get("metadata") or {}
    logical_task_id = result.get("id")

    agent_name = (
        outer_metadata.get("agent_name")
        or _agent_from_task_id(logical_task_id)
        or "unknown"
    )

    base = {
        "case_id": case_id,
        "agent": agent_name,
        "task_id": logical_task_id,
        "ts": status.get("timestamp"),
        "source": "sam",
    }

    status_type = inner_metadata.get("type")

    if status_type == "llm_invocation":
        return {
            **base,
            "event": "thinking",
            "content": _summarise_llm_request(inner_metadata.get("data")),
        }

    if status_type == "llm_response":
        return {
            **base,
            "event": "llm_response",
            "content": _summarise_llm_response(inner_metadata.get("data")),
        }

    if status_type == "tool_invocation_start":
        data = inner_metadata.get("data") or {}
        return {
            **base,
            "event": "tool_call",
            "tool_name": data.get("tool_name"),
            "args": _clip_json(data.get("tool_args"), _TOOL_ARGS_CHAR_CAP),
        }

    # Status messages with no metadata.type often carry streaming text.
    # Fall through and try to surface something readable.
    if _looks_like_text_parts(message):
        text = _first_text_part(message)
        if text:
            return {
                **base,
                "event": "response",
                "content": text[:_THINKING_CHAR_CAP],
            }

    # Unknown — keep it visible but tagged so the frontend's default
    # EventLine renders it rather than silently dropping it.
    return {
        **base,
        "event": "unknown",
        "content": _clip_json(inner_metadata or outer_metadata, _RESULT_CHAR_CAP),
    }


def _agent_from_task_id(task_id: Any) -> str | None:
    if not isinstance(task_id, str):
        return None
    m = _TASK_ID_AGENT_RE.match(task_id)
    return m.group("agent") if m else None


def _summarise_llm_request(data: Any) -> str:
    if not isinstance(data, dict):
        return ""
    # ADK `LlmRequest` model_dump: contents list with role/parts, or
    # model+messages in LiteLLM shape. Extract the most recent user
    # turn's text if we can find it.
    contents = data.get("contents") or data.get("messages") or []
    if isinstance(contents, list):
        for entry in reversed(contents):
            text = _extract_text_from_turn(entry)
            if text:
                return text[:_THINKING_CHAR_CAP]
    model = data.get("model") or ""
    return (f"→ {model}" if model else "LLM invocation")[:_THINKING_CHAR_CAP]


def _summarise_llm_response(data: Any) -> str:
    if not isinstance(data, dict):
        return ""
    # ADK LlmResponse: content.parts[*].text is the usual path; also
    # tool_calls live on content.parts[*].function_call.
    content = data.get("content") or {}
    parts = content.get("parts") if isinstance(content, dict) else None
    if isinstance(parts, list):
        text_chunks = []
        for p in parts:
            if not isinstance(p, dict):
                continue
            t = p.get("text")
            if t:
                text_chunks.append(t)
            fc = p.get("function_call")
            if isinstance(fc, dict) and fc.get("name"):
                text_chunks.append(f"[tool → {fc['name']}]")
        if text_chunks:
            return "\n".join(text_chunks)[:_THINKING_CHAR_CAP]
    return "LLM response"


def _extract_text_from_turn(entry: Any) -> str | None:
    if not isinstance(entry, dict):
        return None
    parts = entry.get("parts")
    if isinstance(parts, list):
        for p in parts:
            if isinstance(p, dict) and p.get("text"):
                return p["text"]
    # LiteLLM shape.
    content = entry.get("content")
    if isinstance(content, str) and content:
        return content
    return None


def _looks_like_text_parts(message: dict) -> bool:
    parts = message.get("parts") if isinstance(message, dict) else None
    return isinstance(parts, list) and any(
        isinstance(p, dict) and p.get("text") for p in parts
    )


def _first_text_part(message: dict) -> str | None:
    for p in message.get("parts") or []:
        if isinstance(p, dict) and p.get("text"):
            return p["text"]
    return None


def _clip_json(value: Any, cap: int) -> str:
    if value is None:
        return ""
    try:
        s = value if isinstance(value, str) else json.dumps(value, default=str)
    except Exception:
        s = str(value)
    return s[:cap]
