"""Locust load test suite for VerdictCouncil API.

Covers the performance targets defined in docs/architecture/12-testing-summary.md:
  - case-processing p95 ≤ 5 s
  - evidence-analysis p95 ≤ 30 s
  - argument-construction p95 ≤ 45 s
  - full pipeline p95 ≤ 3 min (excluding Gate pauses)

Usage
-----
    # Headless (CI mode) — run 60 s burst, 10 users, ramp 2/s:
    locust -f tests/load/locustfile.py \
        --headless -u 10 -r 2 -t 60s \
        --host http://localhost:8000 \
        --html tests/load/report.html

    # Interactive UI (development):
    locust -f tests/load/locustfile.py --host http://localhost:8000

Environment variables
---------------------
    VC_LOAD_USERNAME    judge username to authenticate as (default: judge@example.com)
    VC_LOAD_PASSWORD    password for that user (default: TestPassword123!)
    VC_LOAD_CASE_ID     an existing case UUID to hit pipeline endpoints against
                        (default: empty — case creation task creates one dynamically)

CI integration
--------------
The ``locustfile.py`` is invoked in the CI ``load-tests`` job defined in
``.github/workflows/ci.yml``.  Failure thresholds are enforced via:
    --exit-code-on-error 1
    --check-response-time  (when supported)
The CI job fails if p95 > threshold or error_rate > 5%.

Notes
-----
* This file intentionally has no pytest markers — Locust runs it directly,
  not through pytest.
* ``--csv=results`` emits results.csv / results_failures.csv / results_stats.csv
  which are uploaded as CI artifacts.
"""

from __future__ import annotations

import os
import random
import string
import time
from typing import Any

from locust import HttpUser, TaskSet, between, events, task

# ---------------------------------------------------------------------------
# Configuration (override via env)
# ---------------------------------------------------------------------------

VC_USERNAME = os.environ.get("VC_LOAD_USERNAME", "judge@example.com")
VC_PASSWORD = os.environ.get("VC_LOAD_PASSWORD", "TestPassword123!")
VC_CASE_ID = os.environ.get("VC_LOAD_CASE_ID", "")

# Performance thresholds (milliseconds) — from 12-testing-summary.md
_THRESHOLD_CASE_PROCESS = 5_000      # p95 ≤ 5 s
_THRESHOLD_EVIDENCE = 30_000         # p95 ≤ 30 s
_THRESHOLD_ARGUMENTS = 45_000        # p95 ≤ 45 s
_THRESHOLD_FULL_PIPELINE = 180_000   # p95 ≤ 3 min


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _rand_str(n: int = 8) -> str:
    return "".join(random.choices(string.ascii_lowercase, k=n))


# ---------------------------------------------------------------------------
# Auth + case bootstrap task set
# ---------------------------------------------------------------------------


class AuthMixin:
    """Mixin that handles login before task execution starts."""

    _token_cookie: str | None = None

    def on_start(self):
        """Authenticate once and store the JWT cookie."""
        with self.client.post(
            "/api/v1/auth/login",
            json={"username": VC_USERNAME, "password": VC_PASSWORD},
            catch_response=True,
            name="[auth] login",
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            else:
                resp.failure(f"Login failed: {resp.status_code} {resp.text[:200]}")


# ---------------------------------------------------------------------------
# Task sets
# ---------------------------------------------------------------------------


class CaseCRUDTasks(TaskSet):
    """Lightweight CRUD tasks simulating a judge managing cases."""

    case_ids: list[str] = []

    def on_start(self):
        # Create one case to have something to read
        self._create_case()

    def _create_case(self) -> str | None:
        payload = {
            "title": f"Load test case {_rand_str()}",
            "description": "Auto-generated by Locust load tests.",
            "domain": "traffic_violation",
            "parties": [
                {"name": "Prosecution", "role": "prosecution"},
                {"name": f"Defendant-{_rand_str(4)}", "role": "accused"},
            ],
        }
        with self.client.post(
            "/api/v1/cases",
            json=payload,
            catch_response=True,
            name="[cases] create",
        ) as resp:
            if resp.status_code in (200, 201):
                resp.success()
                data = resp.json()
                case_id = data.get("id") or data.get("case_id")
                if case_id:
                    self.case_ids.append(str(case_id))
                return str(case_id)
            else:
                resp.failure(f"Create failed: {resp.status_code}")
                return None

    @task(5)
    def list_cases(self):
        with self.client.get(
            "/api/v1/cases?limit=20&offset=0",
            catch_response=True,
            name="[cases] list",
        ) as resp:
            if resp.status_code == 200:
                elapsed = resp.elapsed.total_seconds() * 1000
                if elapsed > _THRESHOLD_CASE_PROCESS:
                    resp.failure(f"list_cases p95 exceeded: {elapsed:.0f}ms > {_THRESHOLD_CASE_PROCESS}ms")
                else:
                    resp.success()
            else:
                resp.failure(f"List failed: {resp.status_code}")

    @task(3)
    def get_case(self):
        if not self.case_ids:
            return
        case_id = random.choice(self.case_ids)
        with self.client.get(
            f"/api/v1/cases/{case_id}",
            catch_response=True,
            name="[cases] get",
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            elif resp.status_code == 404:
                resp.success()  # Might have been deleted by another user
            else:
                resp.failure(f"Get failed: {resp.status_code}")

    @task(1)
    def create_case(self):
        self._create_case()

    @task(2)
    def dashboard(self):
        with self.client.get(
            "/api/v1/dashboard/stats",
            catch_response=True,
            name="[dashboard] stats",
        ) as resp:
            if resp.status_code in (200, 404):
                resp.success()
            else:
                resp.failure(f"Dashboard failed: {resp.status_code}")


class HealthCheckTasks(TaskSet):
    """Lightweight health-probe tasks that every VU runs."""

    @task(10)
    def health(self):
        with self.client.get(
            "/health",
            catch_response=True,
            name="[health] check",
        ) as resp:
            if resp.status_code == 200:
                resp.success()
            else:
                resp.failure(f"Health check failed: {resp.status_code}")

    @task(1)
    def pair_health(self):
        with self.client.get(
            "/api/v1/health/pair",
            catch_response=True,
            name="[health] pair",
        ) as resp:
            if resp.status_code in (200, 503):  # 503 = PAIR down (expected in load env)
                resp.success()
            else:
                resp.failure(f"PAIR health failed: {resp.status_code}")


class SSEStreamTasks(TaskSet):
    """SSE subscription task — opens stream for 2 s and closes."""

    _case_id: str | None = None

    def on_start(self):
        self._case_id = VC_CASE_ID or None

    @task
    def subscribe_case_sse(self):
        if not self._case_id:
            return  # Skip if no case ID configured
        start = time.monotonic()
        with self.client.get(
            f"/api/v1/cases/{self._case_id}/stream",
            stream=True,
            catch_response=True,
            timeout=5,
            name="[sse] subscribe",
        ) as resp:
            elapsed = (time.monotonic() - start) * 1000
            if resp.status_code in (200, 204):
                resp.success()
            elif resp.status_code == 404:
                resp.success()  # Case may not be running
            else:
                resp.failure(f"SSE failed: {resp.status_code} ({elapsed:.0f}ms)")


# ---------------------------------------------------------------------------
# User classes
# ---------------------------------------------------------------------------


class JudgeUser(AuthMixin, HttpUser):
    """Simulates a judge performing typical CRUD operations."""

    wait_time = between(1, 3)
    tasks = {CaseCRUDTasks: 4, HealthCheckTasks: 1}

    def on_start(self):
        super().on_start()  # Login


class HealthCheckUser(HttpUser):
    """Simulates a monitoring probe hitting health endpoints."""

    wait_time = between(5, 10)
    tasks = [HealthCheckTasks]


class SSEUser(AuthMixin, HttpUser):
    """Simulates a browser tab holding an SSE connection open."""

    wait_time = between(30, 60)  # SSE holds longer connections
    tasks = [SSEStreamTasks]

    def on_start(self):
        super().on_start()


# ---------------------------------------------------------------------------
# Custom failure thresholds hook (checked after test run)
# ---------------------------------------------------------------------------


@events.quitting.add_listener
def assert_performance_thresholds(environment, **kwargs):
    """Fail the run if p95 latency or error rate exceed configured thresholds."""
    stats = environment.runner.stats

    error_rate = (
        stats.total.num_failures / max(stats.total.num_requests, 1)
    )
    if error_rate > 0.05:
        environment.process_exit_code = 1
        print(
            f"\n[LOAD TEST FAIL] Error rate {error_rate:.1%} exceeds 5% threshold"
        )

    # Check p95 for the most critical endpoints
    for name in ("[cases] list", "[cases] get", "[health] check"):
        entry = stats.entries.get((name, "GET")) or stats.entries.get((name, "POST"))
        if entry and entry.get_response_time_percentile(0.95) > _THRESHOLD_CASE_PROCESS:
            p95 = entry.get_response_time_percentile(0.95)
            environment.process_exit_code = 1
            print(
                f"\n[LOAD TEST FAIL] {name!r} p95={p95:.0f}ms exceeds "
                f"{_THRESHOLD_CASE_PROCESS}ms threshold"
            )
