apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment-api-service.yaml
  - cronjob-stuck-case-watchdog.yaml
  - service-api-service.yaml
  - ingress.yaml
